pipeline:
  test:
    image: croudtech/webapp:2.0.0
    commands:
      - /usr/bin/composer install
      - ./vendor/bin/phpunit -d memory_limit=2G tests
  notify:
    image: drillster/drone-email
    subject: Recurring Task Scheduler Pipeline {{#success build.status}}SUCCESS{{else}}FAILURE{{/success}} Notification
    host: email-smtp.eu-west-1.amazonaws.com
    from: Drone CI <drone@croudcontrol.com>
    recipients: [ jim.robinson@croud.co.uk ]
    secrets: [ EMAIL_USERNAME, EMAIL_PASSWORD ]
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: docker
    template: >
     {{#success build.status}}
       recurring_task_scheduler -> build {{build.number}} succeeded. Good job.
     {{else}}
       recurring_task_scheduler -> build {{build.number}} failed. Fix me please.
     {{/success}}