language: php
php:
- '7.1'
install:
- composer install
notifications:
  slack:
    secure: mXQosxLZ4pgXMITvPsS/0pUW2GwQznROY1sR5mj9QgUnu57zOa7Y/zfCtgIluGzYPOK9E2xyualhg5u6btLdyWdOQ3JGFKUPrD7E697ybZszSSop8rEFVXSxpqP47IG+6a2TyyoV1r8xkRZPAK+Jv7JWWErAwLXndO5iN1whKqIRrCBi+LP2y7Uc8pdFBsNzssfO8cWSG6EPolKcRQ20tOswvwsdKNp25vDXnfe9Rni2XPmjDJudwYvJs2TAVKj3JvLUe2OfhFuPQU8pBQLaEh5fVm95evAQM3YKfMGDSx45exz2EGBPau7QsstoFqEaPx2LIAw6IYfSTIFQXPBXdNfHYfiagFtNbQqAC+wzmRhzdDRZYzRjekwjNTojGZNKhnGr3Cd2Z1ggevBTFgV0xyhbXY/lzNEnWROOEnCfsFsNYkCCMfYAAHGxPUiooiB0lV4JZDdZ2wjTzs/5dRMVwToxoDNx1HV+bYDwTt6hmN9ONutw72kJ2abRcBY8BBrOS7K2BHJ5ynR25rmBhFcXvDnHq+lmxnIMbG0Enwh/UtxCvfphnJvUEEEO6OvzMmASrO6c3uzWHwANGqDDAdF+5RW2TaOLffXRmYap6yHF4JOW2c+qruTtesNjeV2A5TS7o+qcczM85f/PM3yheyMqs4l0yHJnFwVC2MwVAw8QA2Y=
